version: "3"
services:
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    container_name: mysql;
    volumes:
      - ./mysql-volume8/:/var/lib/mysql
#  products:
#     build:
#       dockerfile: Dockerfile
#       context: ./products
#     container_name: products
#     ports:
#       - "8002:8002"
#     restart: always
#     depends_on:
#       - "mysql"
#     volumes:
#       - .:/app
#       - /app/products/node_modules

#     env_file:
#       - ./products/.env.dev
  # identity:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./identity
  #   container_name: identity
  #   ports:
  #     - "8001:8001"
  #   restart: always
  #   depends_on:
  #     - "mysql"

  #   volumes:
  #     - .:/app/
  #     - /app/identity/node_modules
  #   env_file:
  #     - ./identity/.env.dev
  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - products
      - identity
    ports:
      - 80:80